Pin cargo-platform dependency
Cargo-platform no longer works on rustc older than 1.78, whereas skeptic
still does not work on rustc newer than 1.76.

    error: package `cargo-platform v0.1.9` cannot be built because it requires
    rustc 1.78 or newer, while the currently active rustc version is 1.76.0
    Either upgrade to rustc 1.78 or newer, or use
    cargo update cargo-platform@0.1.9 --precise ver
    where `ver` is the latest version of `cargo-platform` supporting rustc 1.76.0